@extends('layouts.app')

@section('content')
    <section class="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#062f3d] via-[#075d62] to-[#0d8a86] px-6 py-16 text-white shadow-2xl sm:px-10 lg:px-16">
        <div class="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-teal-300/20 blur-3xl"></div>
        <div class="relative max-w-3xl"><p class="text-sm font-bold uppercase tracking-[0.25em] text-teal-200">Institut Teknologi Sepuluh Nopember</p><h1 class="mt-5 text-4xl font-black leading-tight sm:text-6xl">Hello, I’m <span class="text-teal-200">Hisyam.</span></h1><p class="mt-6 max-w-2xl text-lg leading-8 text-teal-50/90">Mahasiswa Informatika ITS yang mengeksplorasi data, machine learning, dan pengalaman digital yang bermakna.</p><div class="mt-9 flex flex-wrap gap-3"><a href="{{ route('mahasiswa.detail', ['nrp' => $mahasiswa['nrp']]) }}" class="rounded-full bg-white px-6 py-3 font-bold text-[#075d62] transition hover:-translate-y-1 hover:shadow-lg">Explore my profile ↗</a><a href="{{ route('agent.show') }}" class="rounded-full border border-white/40 px-6 py-3 font-bold transition hover:bg-white/10">View DataAgent.ai</a></div></div>
    </section>
    <section class="mt-12 grid gap-6 lg:grid-cols-5"><a href="{{ route('mahasiswa.detail', ['nrp' => $mahasiswa['nrp']]) }}" class="group rounded-3xl bg-white p-7 shadow-lg shadow-slate-200/60 ring-1 ring-slate-100 transition duration-300 hover:-translate-y-2 hover:shadow-xl lg:col-span-3"><div class="flex items-start gap-5"><div class="grid h-20 w-20 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-teal-500 to-cyan-700 text-3xl font-black text-white shadow-lg">HS</div><div><p class="text-xs font-bold uppercase tracking-widest text-teal-700">Academic profile</p><h2 class="mt-2 text-2xl font-black text-slate-900">{{ $mahasiswa['nama'] }}</h2><p class="mt-1 text-slate-500">{{ $mahasiswa['prodi'] }}</p></div></div><div class="mt-7 flex items-center justify-between border-t border-slate-100 pt-5"><span class="font-mono text-sm text-slate-500">{{ $mahasiswa['nrp'] }}</span><span class="font-bold text-teal-700 transition group-hover:translate-x-1">Full profile →</span></div></a><a href="{{ route('agent.show') }}" class="group rounded-3xl bg-slate-900 p-7 text-white shadow-lg transition duration-300 hover:-translate-y-2 hover:shadow-xl lg:col-span-2"><p class="text-xs font-bold uppercase tracking-widest text-cyan-300">Final project concept</p><h2 class="mt-3 text-3xl font-black">DataAgent<span class="text-teal-300">.ai</span></h2><p class="mt-3 leading-7 text-slate-300">Autonomous AI Agent Suite for end-to-end data analytics.</p><p class="mt-8 font-bold text-teal-300">Meet the agents →</p></a></section>
@endsection
